routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();
Route::resource('foodplace', 'FoodPlaceController');

app/FoodPlace.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class FoodPlace extends Model
{
    use SoftDeletes;
    protected $fillable=
    [
    	'nama','alamat', 'latitude', 'longtitude', 'id_menu'
    ];
    protected $dates= ['deleted_at'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FoodPlaceController.php
<?php

namespace App\Http\Controllers;

use App\FoodPlace;
use Illuminate\Http\Request;

class FoodPlaceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $foodplaces = FoodPlace::orderBy('id', 'DESC')->paginate(5);
        return view('foodplace.index', compact('foodplaces'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('foodplace.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $this->validate($request, [
            'nama' => 'required',
            'alamat' => 'required',
            'latitude' => 'required',
            'longtitude' => 'required',
            'id_menu' => 'required'
        ]);

        $foodplace = FoodPlace::create($request->all());

        return redirect()->route('foodplace.index')->with('message', 'Food Place berhasil Diinputkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\FoodPlace  $foodPlace
     * @return \Illuminate\Http\Response
     */
    public function show(FoodPlace $foodplace)
    {
      
        return view('foodplace.show', compact('foodplace'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\FoodPlace  $foodPlace
     * @return \Illuminate\Http\Response
     */
    public function edit(FoodPlace $foodplace)
    {

        return view('foodplace.edit', compact('foodplace'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\FoodPlace  $foodPlace
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, FoodPlace $foodplace)
    {
        $this->validate($request, [
            'nama' => 'required',
            'alamat' => 'required',
            'latitude' => 'required',
            'longtitude' => 'required',
            'id_menu' => 'required'
        ]);

        $foodplace->update($request->all());

        return redirect()->route('foodplace.index')->with('message', 'Food Place berhasil diubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\FoodPlace  $foodPlace
     * @return \Illuminate\Http\Response
     */
    public function destroy(FoodPlace $foodplace)
    {
        $foodplace->delete();
        return redirect()->route('foodplace.index')->with('message', 'Food Place berhasil dihapus!');
    }
}

resources/views/foodplace/create.blade.php
@extends('layouts.app')

@section('content')
<h4>Food Place Baru</h4>
<form action="{{ route('foodplace.store') }}" method="post">
    {{csrf_field()}}
    <div class="form-group {{ $errors->has('nama') ? 'has-error' : '' }}">
        <label for="nama" class="control-label">Nama</label>
        <input type="text" class="form-control" name="nama" placeholder="Nama Restoran">
        @if ($errors->has('nama'))
            <span class="help-block">{{ $errors->first('nama') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('alamat') ? 'has-error' : '' }}">
        <label for="alamat" class="control-label">Alamat</label>
        <textarea name="alamat" cols="30" rows="5" class="form-control"></textarea>
        @if ($errors->has('alamat'))
            <span class="help-block">{{ $errors->first('alamat') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('latitude') ? 'has-error' : '' }}">
        <label for="latitude" class="control-label">Latitude</label>
        <input type="text" class="form-control" name="latitude" placeholder="Latitude">
        @if ($errors->has('latitude'))
            <span class="help-block">{{ $errors->first('latitude') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('longtitude') ? 'has-error' : '' }}">
        <label for="longtitude" class="control-label">Longitude</label>
        <input type="text" class="form-control" name="longtitude" placeholder="Longtitude">
        @if ($errors->has('longtitude'))
            <span class="help-block">{{ $errors->first('longtitude') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('id_menu') ? 'has-error' : '' }}">
        <label for="id_menu" class="control-label">ID Menu</label>
        <input type="text" class="form-control" name="id_menu" placeholder="ID MENU">
        @if ($errors->has('id_menu'))
            <span class="help-block">{{ $errors->first('id_menu') }}</span>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Simpan</button>
        <a href="{{ route('foodplace.index') }}" class="btn btn-default">Kembali</a>
    </div>
</form>
@endsection

resources/views/foodplace/edit.blade.php
@extends('layouts.app')

@section('content')
<h4>Ubah Data</h4>
<form action="{{ route('foodplace.update', $foodplace->id) }}" method="post">
    {{csrf_field()}}
    {{ method_field('PUT') }}
    <div class="form-group {{ $errors->has('nama') ? 'has-error' : '' }}">
        <label for="nama" class="control-label">Nama</label>
        <input type="text" class="form-control" name="nama" placeholder="nama" value="{{ $foodplace->nama }}">
        @if ($errors->has('nama'))
            <span class="help-block">{{ $errors->first('nama') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('alamat') ? 'has-error' : '' }}">
        <label for="alamat" class="control-label">alamat</label>
        <textarea name="alamat" cols="30" rows="5" class="form-control">{{ $foodplace->alamat }}</textarea>
        @if ($errors->has('alamat'))
            <span class="help-block">{{ $errors->first('alamat') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('latitude') ? 'has-error' : '' }}">
        <label for="latitude" class="control-label">latitude</label>
        <input type="text" class="form-control" name="latitude" placeholder="latitude" value="{{ $foodplace->latitude }}">
        @if ($errors->has('latitude'))
            <span class="help-block">{{ $errors->first('latitude') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('longtitude') ? 'has-error' : '' }}">
        <label for="longtitude" class="control-label">longitude</label>
        <input type="text" class="form-control" name="longtitude" placeholder="longtitude" value="{{ $foodplace->longtitude }}">
        @if ($errors->has('longtitude'))
            <span class="help-block">{{ $errors->first('longtitude') }}</span>
        @endif
    </div>
    <div class="form-group {{ $errors->has('id_menu') ? 'has-error' : '' }}">
        <label for="id_menu" class="control-label">ID Menu</label>
        <input type="text" class="form-control" name="id_menu" placeholder="id_menu" value="{{ $foodplace->id_menu }}">
        @if ($errors->has('id_menu'))
            <span class="help-block">{{ $errors->first('id_menu') }}</span>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Simpan</button>
        <a href="{{ route('foodplace.index') }}" class="btn btn-default">Kembali</a>
    </div>
</form>
@endsection

resources/views/foodplace/index.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('foodplace.create') }}" class="btn btn-info btn-sm">Food Place</a>
    
    @if ($message = Session::get('message'))
        <div class="alert alert-success martop-sm">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-responsive martop-sm">
        <thead>
            <th>ID</th>
            <th>Nama</th>
            <th>Alamat</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>ID Menu</th>

        </thead>
        <tbody>
            @foreach ($foodplaces as $foodplace)
                <tr>
                    <td>{{ $foodplace->id }}</td>
                    <td><a href="{{ route('foodplace.show', $foodplace->nama) }}">{{ $foodplace->nama}}</a></td>
                    <td><a href="{{ route('foodplace.show', $foodplace->alamat) }}">{{ $foodplace->alamat }}</a></td>
                    <td><a href="{{ route('foodplace.show', $foodplace->latitude) }}">{{ $foodplace->latitude }}</a></td>
                    <td><a href="{{ route('foodplace.show', $foodplace->longtitude) }}">{{ $foodplace->longtitude }}</a></td>
                    <td><a href="{{ route('foodplace.show', $foodplace->id_menu) }}">{{ $foodplace->id_menu }}</a></td>
                    <td>
                        <form action="{{ route('foodplace.destroy', $foodplace->id) }}" method="post">
                            {{csrf_field()}}
                            {{ method_field('DELETE') }}
                            <a href="{{ route('foodplace.edit', $foodplace->id) }}" class="btn btn-warning btn-sm">Ubah</a>
                            <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/foodplace/show.blade.php
@extends('layouts.app')

@section('content')
<h4>{{ $foodplace->nama }}</h4>
<p>{{ $foodplace->alamat }}</p>
<p>{{ $foodplace->latitude }}</p>
<p>{{ $foodplace->longtitude }}</p>
<p>{{ $foodplace->id_menu }}</p>
<a href="{{ route('foodplace.index') }}" class="btn btn-default">Kembali</a>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <title>FOOD POINT</title>
    <style>
        .martop-sm {margin-top: 15px;}
        .martop-lg {margin-top: 70px;}
    </style>
</head>
<body>
    <div class="container martop-lg">
        <div class="panel panel-default">
            <div class="panel-body">@yield('content')</div>
        </div>
    </div>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>